import React, { Fragment } from "react"
import { Trans, SelectOrdinal } from '@lingui/macro';
import * as common from './commonTranslations';
import { BsArrowUp, BsArrowDown } from 'react-icons/bs';

const comboTricksTitle = (trickCount) => <SelectOrdinal id="sortingCategory.comboTricksTitle" value={trickCount} other="# Trick Combo" />;

export const trickSortingSchemes = [
  {"name": <Fragment><Trans id={common.level.id} /> <BsArrowUp className="icon-white" /></Fragment>,
    "id": 0,
    "sortFunc": (a, b) => (a.difficultyLevel - b.difficultyLevel),
    "catName": <Trans id={common.level.id} />,
    "attributeFunc": (a) => a.difficultyLevel,
    "showCategory": true,
  },
  {"name": <Fragment><Trans id={common.level.id} /> <BsArrowDown className="icon-white" /></Fragment>,
    "id": 1,
    "sortFunc": (a, b) => (b.difficultyLevel - a.difficultyLevel),
    "catName": <Trans id={common.level.id} />,
    "attributeFunc": (a) => a.difficultyLevel,
    "showCategory": true,
  },
  {"name": <Fragment><Trans id={common.stickFrequency.id} /> <BsArrowUp className="icon-white" /></Fragment>,
    "id": 2,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (a.stickFrequency - b.stickFrequency);return 0.1;},
    "catName": <Trans id={common.stickFrequency.id} />,
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
  {"name": <Fragment><Trans id={common.stickFrequency.id} /> <BsArrowDown className="icon-white" /></Fragment>,
    "id": 3,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (b.stickFrequency - a.stickFrequency);return 1;},
    "catName": <Trans id={common.stickFrequency.id} />,
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
];

export const comboSortingSchemes = [
  {"name": <Fragment><Trans id={common.length.id} /> <BsArrowUp className="icon-white" /></Fragment>,
    "id": 0,
    "sortFunc": (a, b) => (a.numberOfTricks - b.numberOfTricks),
    "catName": comboTricksTitle,
    "attributeFunc": (a) => a.numberOfTricks,
    "showCategory": true,
  },
  {"name": <Fragment><Trans id={common.length.id} /> <BsArrowDown className="icon-white" /></Fragment>,
    "id": 1,
    "sortFunc": (a, b) => (b.numberOfTricks - a.numberOfTricks),
    "catName": comboTricksTitle,
    "attributeFunc": (a) => a.numberOfTricks,
    "showCategory": true,
  },
  {"name": <Fragment><Trans id={common.stickFrequency.id} /> <BsArrowUp className="icon-white" /></Fragment>,
    "id": 2,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (a.stickFrequency - b.stickFrequency);return 0.1;},
    "catName": <Trans id={common.stickFrequency.id} />,
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
  {"name": <Fragment><Trans id={common.stickFrequency.id} /> <BsArrowDown className="icon-white" /></Fragment>,
    "id": 3,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (b.stickFrequency - a.stickFrequency);return 1;},
    "catName": <Trans id={common.stickFrequency.id} />,
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
];
