export const trickSortingSchemes = [
  {"name": "Level Upwards",
    "id": 0,
    "sortFunc": (a, b) => (a.difficultyLevel - b.difficultyLevel),
    "catName": "Level",
    "attributeFunc": (a) => a.difficultyLevel,
    "showCategory": true,
  },
  {"name": "Level Downwards",
    "id": 1,
    "sortFunc": (a, b) => (b.difficultyLevel - a.difficultyLevel),
    "catName": "Level",
    "attributeFunc": (a) => a.difficultyLevel,
    "showCategory": true,
  },
  {"name": "StickFrequency Upwards",
    "id": 2,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (a.stickFrequency - b.stickFrequency);return 0.1;},
    "catName": "StickFrequency",
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
  {"name": "StickFrequency Downwards",
    "id": 3,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (b.stickFrequency - a.stickFrequency);return 1;},
    "catName": "StickFrequency",
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
];

export const comboSortingSchemes = [
  {"name": "Length Upwards",
    "id": 0,
    "sortFunc": (a, b) => (a.numberOfTricks - b.numberOfTricks),
    "catName": "Trick Combos",
    "attributeFunc": (a) => a.numberOfTricks,
    "showCategory": true,
  },
  {"name": "Length Downwards",
    "id": 1,
    "sortFunc": (a, b) => (b.numberOfTricks - a.numberOfTricks),
    "catName": "Trick Combos",
    "attributeFunc": (a) => a.numberOfTricks,
    "showCategory": true,
  },
  {"name": "StickFrequency Upwards",
    "id": 2,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (a.stickFrequency - b.stickFrequency);return 0.1;},
    "catName": "StickFrequency",
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
  {"name": "StickFrequency Downwards",
    "id": 3,
    "sortFunc": (a, b) => {if (a.stickFrequency >= 0) return (b.stickFrequency - a.stickFrequency);return 1;},
    "catName": "StickFrequency",
    "attributeFunc": (a) => a.stickFrequency,
    "showCategory": false,
  },
];
