// increase this manualy if you update the predefinedTricks
export const predefinedTricksVersion = 8;
// predefinedTricks have to have an id above 10000
export const predefinedTricks = `id,technicalName,alias,establishedBy,yearEstablished,linkToVideo,videoStartTime,videoEndTime,startPos,endPos,difficultyLevel,description,tips,recommendedPrerequisites
10005,Sofa Roll,,Samuel Volery,2016,https://www.youtube.com/watch?v=Ugw1gRm-T0U,,,SOFA,SOFA,1,"Sit in Sofa, grab the line with both hands and press the line against your butt/thighs. Then throw yourself forward or backward, initiating the roll. To stop the roll, extend your legs.",Leash to the side can help prevent bad falls; If you fall into a backlever position let go of the line in order to save your shoulders; You can practice this trick with a hangover clipped in to save energy and get familiar with the movement without fear of falling badly,
10006,Belly Roll,,,,https://www.youtube.com/watch?v=1qJJ26dPKyc,,,BELLY,BELLY,1,With both hands on the line supporting your weight you lie on your belly and roll forward (or backward) around the line.,You can try this trick clipped into the hangover first to save energy while familiarizing yourself with the movement.,
10007,Chest Roll,,,,https://www.youtube.com/watch?v=ih6Rx-UpBfw&t=333,333,339,CHEST,CHEST,1,"From lying on your chest get some momentum with your free arm and leg, hook the line with one foot and then roll around the line grabbing it with both hands. Land back in chest.","You can wrap the foot around the line to avoid falling away from the line. Alternatively, you can press it against the line from below; You can try this trick clipped into a hangover at first to familiarize yourself with the movement.",
10011,Korean Roll,,,,https://www.youtube.com/watch?v=yze-WPst9R8,,,KOREAN,KOREAN,1,"Sit in Korean, grab the line with one hand in front of you and one hand behind you and let yourself fall to the side. Land back in Korean.","Start the movement while the line moves upwards; You can try this trick clipped into a hangover first; Sometimes called ""Harry Potter Roll""",
10225,Sofa 270 to Korean,Panic,,,https://www.youtube.com/watch?v=12HbVhoFloM,,,SOFA,KOREAN,1,"From Sofa you start a 180 FS spin, grab the line on your side with both hands and swing the far leg over the line to land in Korean.",Keep your center of gravity above the line.,
10004,Hammock Roll,,Samuel Volery,2016,https://www.youtube.com/watch?v=maY2RjAJs1g,,,BACK,BACK,2,Lie on your back and grab the line behind your head with both hands. Hook one foot under the line and roll around the line landing again in Backbounce.,"As soon as you rotated all the way, let go with your hands and put your arms to the side to stop the roll. Letting go of the line feels counterintuitive, but it really helps to land the trick.",
10000,Sofa 270 Korean Roll,Panic Roll,Jediah Doohan,,https://www.youtube.com/watch?v=12HbVhoFloM,,,SOFA,KOREAN,2,Sit in Sofa position grab the line to the side of you with hands facing behind you. On the way up in the bounce dive down where your hands are and roll around the line. Land in Korean or Chest. Essentially you perform a 270 spin combined with a roll around the line.,It helps to separately practice the spin of the leg (Panic) and the roll around the line and then work to combine both at the same time.,10225
10001,Side Sofa Roll,Utinni Roll,Michele Eibeck,2021,https://www.instagram.com/p/CNYQEb4Jt1M/,,,SOFA,SOFA,2,Start in Sofa. Both hands next to you (right or left) holding on to the line. Then do a Sofa Roll with your body leaning towards the line where your hands are. To land the trick put the hands back to normal as you would when sitting in Sofa.,,10005
10003,Sofa Roll from Korean,Richy Roll,Richard Schupisser,,https://youtu.be/yzx3j2WKvGA?t=15,15,21,KOREAN,SOFA,2,From Korean swing one leg over the line and immediately after you start the leg swing initiate a roll to finish as a Sofa Roll.,Be comfortable with Sofa Rolls first.,10005
10012,Back Korean Roll to Sofa,,Sakalomo,2021,https://youtu.be/7yLCyoHgUS0?t=783,783,790,KOREAN,SOFA,3,"Do a Back Korean Roll with both hands in front. During the roll, pass the front leg between you and the line to land in Sofa. ",,
10014,Expo Buddha Roll,,Eli Ellis,2020,https://youtu.be/hsALSrUdryU?t=29,30,33,BUDDHA,BUDDHA,999,"Sit in Expo Buddha, grab the line both hands on the sides, roll around the line, land again in Expo Buddha.",,
10015,Fake 360 Korean Roll,Flowflip,,,https://youtu.be/12HbVhoFloM?t=199,199,,KOREAN,CHEST,2,"From Korean, combine a 360 spin with a Korean roll around the line. Either start or land in Switch Korean. Similar to a Panic Roll but you start from Korean turned 90 further away to where you want to go.",Learn how to do a Panic Roll first. Then think of it as a Panic Roll from Korean.,10000;10224
10016,Panic Roll to Sofa,,Salomé Cholet,2021,https://youtu.be/7yLCyoHgUS0?t=491,491,496,SOFA,SOFA,3,Do a Panic Roll but before you land throw your second leg on the other side of the line as well to land back in Sofa.,,10000
10017,Backbounce to Chest Roll,,,,https://www.youtube.com/watch?v=ih6Rx-UpBfw&t=478,478,483,BACK,CHEST,2,From Backbounce move forward like you are going to Chest but add a Chest Roll.,,10007
10018,Backbounce Panic Roll,,,,https://www.youtube.com/watch?v=LPsuhcOZd0Q,,,BACK,KOREAN,3,From Backbounce swing one leg to other side and then perform a Panic Roll in the opposite direction. ,,10000
10020,Double Hammock Roll,,,,https://youtu.be/Ej2ocABoNC4?t=19688,19688,19693,BACK,BACK,3,Two Hammock Rolls in one bounce.,,10004
10021,Back Roll Twist,,,,https://youtu.be/rWqH_51ztQA?t=3487,3487,3493,BACK,KOREAN,3,"While doing the second half of a Back Roll, also turn once around the line, so do a Back Roll with a Korean Roll at the end.","For some people, this happens automatically when they try a Back Roll with bad timing. If you're not one of those, try adding a Korean Roll in the second half of the Back Roll.",
10024,Korean 270 Spin to Back Belly Roll,Underflip,Augustin Moinat,2021,,,,KOREAN,BELLY,2,Spin with one leg 270 degrees from Korean to Belly into a Back Belly Roll.,Be comfortable with Back Belly Rolls first; Start the spin with the intention of finishing as a Back Belly Roll.,10006
10184,Sit to Feet,,,,https://www.youtube.com/watch?v=rdV2Jhi6U5Y,,,SIT,STAND,2,"From Sit you stand up on the top of the bounce. If you don't have enough momentum, you can pull on the line with one arm.",Learning this is a lot about learning the correct timing which is doing the trick at the top of the bounce when you feel weightless.,
10185,Korean Bounce,,,,https://www.youtube.com/watch?v=1hPL5d3en8c,,,STAND,KOREAN,2,From standing on the line you let the line come towards your body on the top of the bounce and then slide your feet off the line to land in Korean.,,
10187,Chest Bounce,,,,https://www.youtube.com/watch?v=Z11fkcCv_Qo,,,STAND,CHEST,2,On the way to the top of the bounce you let the line come towards your body and grab it with one hand. Slide your front foot off the line and with your hand controlling the line you drop down to chest.,It can help to practice briefly grabing the line at the top of the bounce while bouncing in normal to learn to let the line come to you instead of you droping down to the line.,
10191,Soup to Feet,,,,https://www.youtube.com/watch?v=-xz9Ex3IE-M,,,SOUP,STAND,2,"From Soup you stand up on the top of the bounce. If you don't have enough momentum, you can pull the line with one arm.",,10184
10192,Soup Bounce,,,,https://www.youtube.com/watch?v=-xz9Ex3IE-M,,,STAND,SOUP,2,From standing on the line you let the line come towards your body on the top of the bounce and sit down keeping one foot on the line.,Feels like sitting down on something behind you; Don't try to grab the line in case you loose the balance; It can help to practice Korean bounces first and then Soup bounces.,10185
10209,180 Chest Roll from Korean,Mini-Fireflip,Salomé Cholet,2021,https://youtu.be/rWqH_51ztQA?t=14839,14839,14843,KOREAN,KOREAN,2,From Korean grab the line behind you and go into a Front Chest Roll. Land back in Korean looking at the other anchor.,,
10224,Korean 360,Flow,,,https://www.youtube.com/watch?v=12HbVhoFloM,,,KOREAN,KOREAN,2,From Korean you grab the line with both hands behind you and then swing your far leg over the line twice to do a 360 landing back in Korean.,Practice the same movement from Sofa first (= Panic).,10225
10275,Back Sofa Roll from Korean,Back Richy Roll,Richard Schupisser,,https://youtu.be/Ej2ocABoNC4?t=18057,18057,18061,KOREAN,SOFA,2,From Korean let yourself fall to the side and immediately after you start the roll swing one leg over the line to finish the roll as a Back Sofa Roll.,,
10279,Petit Trick,,Salomé Cholet,2022,https://youtu.be/Nk-wk2kYRso?t=109,109,112,KOREAN,KOREAN,3,"From Korean, grab the line in front of you with both hands. Shift your weight onto your arms, swing one leg over the line and start bringing it to the front. Lean backwards, release your front hand and swing the same leg as before back over the line. Finish sitting in Korean.",,
10019,Backbounce Richy Roll,,,,https://www.youtube.com/watch?v=uuFlRIMmP8M&t=199,199,203,BACK,SOFA,3,From Backbounce get back up into Korean and in one fluid motion kick one leg over the line to go into a Sofa Roll.,Start the motion of getting up from Backbounce to Korean really early in the upward motion of the line.,10003
10022,Sofa Roll 360,,Anthony Boulay,,https://www.youtube.com/watch?v=ekkrE58S4O8,,,SOFA,SOFA,4,Start a Belly Roll from Sofa and add a 180 at the end.,,10222
10023,Hammock Roll from Feet,,Augustin Moinat,2021,,,,STAND,BACK,5,"Let the line come to your butt and grab it right behind your butt with one hand and then go to Backbounce, grab the second hand behind your head, hook with one foot and do a Hammock Roll. ",,10004
10025,Back Roll Twist from Feet,Escoba Roll,Sakalomo,2021,https://www.instagram.com/p/CMm5lqolNs4/,,,STAND,CHEST,999,Do a Back Roll from Feet but with a roll around the line as well.,,
10026,Back Korean Roll BS 180,Richard Roll,Sakalomo,2021,https://youtu.be/7yLCyoHgUS0?t=694,694,698,KOREAN,KOREAN,4,"Do a Back Korean Roll, pass the front leg over the line to be in Sofa, pass the back leg over the line to end in Korean facing the other anchor.",,
10027,Nevermind BS 360 to Chest,Spiral,Sakalomo,2021,https://youtu.be/7yLCyoHgUS0?t=752,752,761,NEVERMIND,CHEST,4,Do a Nevermind up but instead of going to Feet you spin 360 backside and land in Chest.,,
10028,Double Double Drop Knee Roll,,Davis Hermes,2021,https://youtu.be/VP49hErTqM0?t=125,125,130,DOUBLE DROP KNEE,DOUBLE DROP KNEE,999,Double Roll in Double Drop Knee.,,
10029,Inward Drop Knee Spin to Front Sofa Roll,,Davis Hermes,2021,https://youtu.be/VP49hErTqM0?t=97,97,102,INWARD DROP KNEE,SOFA,999,"Start from Inward Drop Knee, take the front foot off the line to spin 270 to go into a Front Sofa Roll.",,
10032,Sick Nasty to Chest,Nasty Chest,Eli Ellis,2020,https://www.instagram.com/p/CJeCTdHBaUn/,,,SOFA,CHEST,3,Sick Nasty landing in Chest.,,
10035,Sick Nasty to Chest Roll,Nasty Chest Roll,Eli Ellis,2020,https://www.instagram.com/p/CJeCTdHBaUn/,,,SOFA,CHEST,4,Sick Nasty to Chest Roll.,,
10037,Half Back Roll,,Guillaume Fontaine,2017,https://www.youtube.com/watch?v=O_E_2cB0Pcw&t=4,4,7,BACK,SHOULDER,4,From Backbounce do a Back Roll but stop in Shoulderstand.,,10047
10038,FS 360 to Chest,Dirty Bastard,Ian Eisenberg,2021,https://www.youtube.com/watch?v=A8O3iGYGPPk&t=39,39,41,STAND,CHEST,4,From standing do a 360 spin and land in Chest.,,
10039,Antihero,,Ian Eisenberg,2020,https://youtu.be/V0fMaONFvVY,,138,ROCKET,SOFA,4,"Starting from Rocket, initiate a frontflip motion and let go of one hand, bring both legs over the line to land in Sofa.",,
10041,NH Korean Roll from Feet,California Roll,Ian Eisenberg,2020,https://youtu.be/T27UrrWAr7A,,,STAND,KOREAN,999,From standing let the line come to your kneepit and roll to the side landing in Korean.,,
10043,Rocket Mount to Sofa,,Samuel Volery,2017,https://youtu.be/hsALSrUdryU?t=73,73,78,ROCKET,SOFA,4,From Rocket pull yourself up and then swing the legs over the line in a Sick Nasty motion. You have to let go off the line with one hand so your legs can pass to land in Sofa. Alternatively you can also thread both legs in between your arms and the line to go to Sofa.,,
10045,Triple Hammock Roll,,Tlaloc Moctezuma-Burns,2020,https://www.youtube.com/watch?v=Se5XNo0RSP8&t=557,557,562,BACK,BACK,999,Three Hammock Rolls in one bounce.,,
10046,Back Roll from Back to Back,Back Magic,,,https://www.youtube.com/watch?v=-HEZdGIakVQ,,,BACK,BACK,3,Back Roll directly into Backbounce.,,10047
10047,Back Roll from Back,,,,https://youtu.be/9pi0GYhBvdo?t=13,13,19,BACK,KOREAN,2,Choose a shoulder that you will roll over to do this trick and put the leash on the side of this shoulder. From Backbounce wait until you are at the very top of the bounce and then pull yourself back over the shoulder and land in Korean.,Have the leash on the same side as the shoulder you roll over.,
10048,Half Front Roll,,,,,,,SHOULDER,KOREAN,3,"Arrange the leash such that it's hanging down on the side of the shoulder that you are doing the shoulderstand from. Start with the shoulderstand and wait until you're at the top of the bounce. Then push yourself to the front by pushing with your hands off of the line, roll over your back and finish the trick by landing in Korean.",If you are on the right shoulder try to thread your right arm through the leash so you don't end up with the leash stuck on your shoulder.;Often you will slightly overrotate this trick and it can help to grab with both hands in front of you to stop the momentum.,
10052,Makako,,Sakalomo,2021,https://youtu.be/44gWgvZrso4,,,NEVERMIND,BELLY,3,"Hang in Nevermind, thread the leg that is free through your leg and the closer arm and kick through to go to a Back Belly Roll.",,
10179,Belly to Feet,,,,,,,BELLY,EXPOSURE,3,"From Belly lift one foot up on the line, remove the hand on the same side to help you balance and then press the line down with this foot and the other hand to get the second foot up.",,
10180,Sofa to Feet,,,,https://www.youtube.com/watch?v=_CqGa-iBrHE,,,SOFA,EXPOSURE,3,"From Sofa lift one foot up on the line, remove the hand on the same side to help you balance and then press the line down with this foot and the other hand to get the second foot up.","You might need to shift your weight to the opposite side of the foot you are trying to get onto the line; If you have access to a rodeoline with mats, this is a trick you can practice there first.",
10181,Korean to Feet,,,,https://www.youtube.com/watch?v=1hPL5d3en8c,,,KOREAN,STAND,3,From Korean you get both feet on top of the line at the same time followed by a Sit Mount in the same bounce or you put one foot on the line followed by a Soup to Feet in the same bounce.,"Depending on your preferred variation, practice Sit to Feet or Soup to Feet first and then korean to feet will be a natural upgrade when you have the former solid enough.",10184;10191
10182,Back to Feet,,,,https://www.youtube.com/watch?v=MpfpSkwcqsg,,,BACK,STAND,3,"From Backbounce go to Korean and add a Korean to Feet in the same bounce. Alternatively, you can hook the line with one foot to assist pulling yourself up.","Depending on your preferred variation, practice Sit to Feet or Korean to Feet first.",10184;10181
10183,Chest to Feet,,,,https://www.youtube.com/watch?v=Z11fkcCv_Qo,,,CHEST,STAND,3,From Chest you push the line down with one arm and the back foot in order to put your front foot on the line.,,
10186,Back Bounce,,,,https://www.youtube.com/watch?v=MpfpSkwcqsg,,,STAND,BACK,3,"From standing on the line you let the line come towards your body on the top of the bounce and when your butt is on the line, slide your feet off the line and lean all the way back to land in Back.","Learn a Korean Bounce first, practice leaning back from Korean to Back, and then combine both motions into one bounce.",10185
10188,Sit Bounce,,,,https://www.youtube.com/watch?v=rdV2Jhi6U5Y,,,STAND,SIT,3,From standing on the line you let the line come towards your body on the top of the bounce and sit down keeping both of your feet on the line.,"Feels like sitting down on something behind you; Don't try to grab the line in case you loose your balance; It can help to practice Korean bounces first, then Soup bounces and then Sit bounces.",10185;10192
10189,Sofa Bounce,,,,https://www.youtube.com/watch?v=_CqGa-iBrHE,,,EXPOSURE,SOFA,3,From Exposure let the line come towards your body and grab the line with both hands then slide your feet off to land in Sofa.,It can help to practice briefly grabing the line at the top of the bounce while bouncing in Expo; This way you can learn to let the line come towards your butt instead of you droping down to Sofa.,
10190,Belly Bounce,,,,,,,EXPOSURE,BELLY,3,From Exposure let the line come towards your body and grab the line with both hands then slide your feet off to land in Belly.,,
10213,Reverse Panic Roll,,,,,,,KOREAN,SOFA,3,From Korean you do a 270 BS spin to the front and then go into a Front Sofa Roll.,,10000
10215,Reverse Flowflip,Wolf Flip,,,,,,KOREAN,KOREAN,4,"From Korean initiate a 360 BS spin to the front and simultaneously start a roll backwards, spin for a full 360 to land back in Korean after the roll is finished.",,10015
10222,Sofa 360,,,,,,,SOFA,SOFA,3,From Sofa do a 360 spin by doing a 180 to Belly and another 180 from Belly to Sofa. ,You can start by practicing the 180 from Belly to Sofa; You need to find your balance over the line and to land it you need to stick your butt out.,
10278,Reverse Flow,Wolf,,,https://youtu.be/d5GTyM0ReFE?t=45,45,50,KOREAN,KOREAN,3,"From Korean, grab the line in front of you and pass one leg over the line twice (first behind you, at the end in front of you) to do a 360 spin. It is the inverse motion of a Flow.",,10224
10280,Reverse Panic,,,,,,,KOREAN,SOFA,3,"From Korean, grab the line in front of you and pass one leg over the line to do a 270 spin landing in Sofa. It is the inverse motion of a Panic.",,10225
10036,Nevermind,,Friedi Kuehne,2015,https://www.youtube.com/watch?v=JXLw6K-AX7I,,,NEVERMIND,STAND,4,"From the catch position (Nevermind), pull yourself up, put the hooking foot on top of the line, and push yourself up to put the second foot back on the line.",,
10044,Sick Nasty,Flare,Samuel Volery,2018,https://www.youtube.com/watch?v=_xAtTSwu7M8,,,SOFA,SOFA,4,From Sofa you grab the line next to you with both hands and swing the legs over the line and around behind you and again over the line on the other side of your hands back to Sofa.,,
10051,Shoulder Roll,,Anthony Boulay,,https://youtu.be/hsALSrUdryU?t=81,81,85,SHOULDER,SHOULDER,4,"From Shoulderstand, tuck your legs, roll to one side and extend your legs for the landing back in Shoulderstand.",,
10053,FS 360 Butt Flatspin,Butter,Tlaloc Moctezuma-Burns,2021,https://youtu.be/RDVaUFdqMmE?t=237,237,241,SOFA,SOFA,4,In Butt grab the line with the front hand behind you. Then pull with that arm to do a 360 landing back in Sofa.,,
10054,Rocket Mount to Back Sofa Roll,,Sakalomo,2020,https://youtu.be/n_YEN0Yva5I?t=70,70,76,ROCKET,SOFA,5,From Hanging swing your legs beside your hands (similar to a Sick Nasty movement) and go into a Back Sofa Roll.,,
10056,Belly Roll to Feet,,Enzo Fuchs,2018,https://www.youtube.com/watch?v=qUxUNfgvoPs&t=107,107,110,BELLY,EXPOSURE,5,From Belly turn one time around the line and land in Exposure in one bounce.,,10006
10057,Chest Roll to Front Roll,,Guillaume Fontaine,2017,https://youtu.be/O_E_2cB0Pcw?t=40,40,44,CHEST,KOREAN,5,Start by doing a Chest Roll and then do a Front Roll by pushing with one foot off the line.,,
10058,FS 360 Roll Down to Chest,,Ian Eisenberg,2021,https://www.youtube.com/watch?v=A8O3iGYGPPk&t=86,86,96,STAND,CHEST,5,From standing do a 360 spin while doing a roll around the line and land in Chest.,,
10059,Reverse Rocket Mount to Sofa,Rock'n'Roll,Ian Eisenberg,2020,https://www.youtube.com/watch?v=5rGCjINEs0Q&t=39,39,43,ROCKET,SOFA,4,From Rocket do a Reverse Rocket Mount but instead of going to Feet you land in Sofa.,,
10060,Shrimpflip,,Ian Eisenberg,2021,https://youtu.be/7yLCyoHgUS0?t=1501,1501,1508,ROCKET,ROCKET,4,"From the Rocket you kick your feet through your arms between the line and your body, regrab the line and land back in Rocket.",,
10061,Cordova Roll,,Ian Eisenberg,2020,https://youtu.be/Ab2gW1rv5e8?t=58,58,63,ROCKET,ROCKET,5,Start like a Reverse Rocket Mount and go into a Double Drop Knee position but then fully extend your hips while keeping the line at your ankles behind your back. Roll around the line and end up back in Rocket.,,
10062,Rocket 360 to Rocket,Full Rocket,Ian Eisenberg,2021,https://youtu.be/aYsX0kpCnAg?t=23,23,31,ROCKET,ROCKET,5,From Rocket do a 360 around the horizontal axis perpendicular to the line and land again in Rocket.,,
10063,Rocket Roll 180 to Sofa,Rocket Rewind,Ian Eisenberg,2021,https://youtu.be/aYsX0kpCnAg?t=6,6,14,ROCKET,SOFA,5,Start by doing a Rocket Mount but then go into a Belly Roll finishing with a 180 to Sofa.,Get a lot of momentum for the Rocket Roll and in the end do a 180 and stick your butt out as in the Sofa Roll 360.,
10066,Soup Roll to Feet,Can of Soup,Justin Wagers,2019,https://youtu.be/xqblad7pNLA?t=300,300,316,SOUP,STAND,4,"From Soup, you grab one hand in front and one behind, you roll to the side of the leg on the line, put the second foot up, and pull yourself up to land to Feet in normal stance.",,
10068,Sick Nasty Roll,,Samuel Volery,2019,https://youtu.be/uOuqykzwN7w?t=65,65,70,SOFA,SOFA,4,Sick Nasty with an additional Back Sofa Roll in the same bounce.,Regrab with the far hand to get into the Back Sofa Roll.,10044;10071
10069,Sofa 360 to Feet,Baguette,Tlaloc Moctezuma-Burns,2020,https://youtu.be/hsALSrUdryU?t=49,49,53,SOFA,EXPOSURE,5,"From Sofa you do a 360, put the outter foot on the line first and then put the second foot on to land in Exposure.",,10222
10070,Chest Roll to Feet,,,,https://www.youtube.com/watch?v=qUxUNfgvoPs&t=35,35,38,CHEST,STAND,4,Do a Chest Roll and in the end of the roll push yourself away from the line to put your front foot on.,,
10071,Fake Sick Nasty Roll,,,,https://youtu.be/hsALSrUdryU?t=153,153,157,KOREAN,SOFA,4,Sick Nasty Roll but starting from Korean.,,10044
10072,Sick Nasty to Feet,Flare to Feet,,,https://youtu.be/Ej2ocABoNC4?t=18159,18159,18164,SOFA,EXPOSURE,4,From Sofa you grab the line next to you with both hands and swing the legs over the line and around behind you and then you land in Exposure on the other side of your hands.,,10044
10073,Obi Wan,,,,,,,ROCKET,STAND,5,"Similar to Rocket Mount. Instead of putting both feet between your hands, put one foot outside of your hands, then put the second foot between the hands to land in Exposure.",,
10169,Back Can of Soup,,Ian Eisenberg,2021,https://youtu.be/IDYpoOE8Kq8?t=32,32,46,SOUP,STAND,4,From Soup you roll to the side in the direction of your leg that is hanging down and land to Feet in normal stance.,,
10199,Sofa Roll to Feet,,,,https://youtu.be/rWqH_51ztQA?t=12678,12678,12682,SOFA,EXPOSURE,4,"Do a Sofa Roll and during the roll you lean a bit to the side so you can get one foot on the line, to finish the roll you get the second foot up and stand up.",An easier variation is to already start with one foot on the line when you start the roll.,10180
10200,Back Sofa Roll to Feet,,,,,,,SOFA,EXPOSURE,4,"Do a Back Sofa Roll and during the roll you lean a bit to the side so you can get one foot on the line, to finish the roll you get the second foot up and stand up.",An easier variation is to already start with one foot on the line when you start the roll.,10180
10204,Rocket Nasty,,Ian Eisenberg,2021,,,,ROCKET,ROCKET,5,"It's like a Sick Nasty from Rocket to Rocket, but passing the legs over the line to the front.",,
10205,Rocket Mount to DDK,,Enzo Fuchs,,,,,ROCKET,DOUBLE DROP KNEE,5,Rocket Mount landing in Double Drop Knee.,,
10206,Orbital 180,Fake Orbital,,,,,,STAND,CHEST,4,Orbital 180 landing in Chest. The 180 makes it easier compared to the normal Orbital. Also called Norbital.,,
10210,Fireflip to Shoulder,,Samuel Volery,2022,https://www.instagram.com/p/CYPMq9BJg55/,,,KOREAN,SHOULDER,5,From Korean grab the line behind you and go into a Front Chest Roll. Land on your shoulder to finish the trick.,,10209
10221,Korean Pop,Sushi,Ian Eisenberg,2021,https://youtu.be/7yLCyoHgUS0?t=1322,1322,1323,STAND,STAND,4,Korean from Feet and Korean to Feet in one bounce. You have to let the line pop at the beginning.,Consider buying a cup to protect your genitals (applies to men and women).,
10223,Nevermind 180,,Sebastian Egger,2021,https://youtu.be/Ej2ocABoNC4?t=22796,22796,22802,NEVERMIND,EXPOSURE,5,Start as you would for a Nevermind but then use your foot that is in contact with the line to initiate a FS spin and do a 180 before you land in Exposure.,,10036
10226,Richy Roll to Feet,,,,,,,KOREAN,EXPOSURE,5,Front Sofa Roll to Feet but starting from Korean so you have to swing one leg over the line first.,,10199
10227,Back Richy Roll to Feet,,,,,,,KOREAN,EXPOSURE,5,Back Sofa Roll to Feet but starting from Korean so you have to swing one leg over the line first.,,10200
10228,360 Spin,,,,,,,STAND,STAND,5,"Do a 360 spin, restepping with your feet twice.",,
10230,Butter Roll,,,,,,,SOFA,SOFA,5,From Butt grab the line with one hand behind your back. With this hand you pull yourself to do a 360 Butt Flatspin and add a Back Sofa Roll in the end.,,10053
10237,One hand one foot Can of Soup,Pastisroll,Oscar Defoor,2021,,,,SOUP,STAND,5,Can of soup with only using the back hand and the front foot hooking the line.,,
10281,Double Drop Knee Roll,,,,,,,DOUBLE DROP KNEE,DOUBLE DROP KNEE,4,From Double Drop Knee grab the line with both hands and roll to the front landing back in Double Drop Knee.,,
10042,Feet to Shoulder,Kamikaze,Samuel Volery,,https://youtu.be/9Ab1JPDJR-I?t=234,234,237,STAND,SHOULDER,4,"From Standing, grab the line with your hands, take off your front foot, and use the back foot to push yourself into the Shoulderstand.",,
10050,Panic Roll to Feet,,Anthony Boulay,,https://www.youtube.com/watch?v=hQaJ54xvfOA,,,SOFA,EXPOSURE,5,Do a Panic Roll and put your back foot onto the line. When you finished the rotation put the second foot up and stand up.,During the roll get your far foot on the line. At the end of the roll get your second foot up on the line.,10000
10067,Rocket Mount,,Samuel Volery,2017,https://youtu.be/zSfwTW4vJas,,,ROCKET,EXPOSURE,5,"At the bottom of the bounce, kick your legs to the back, immediately afterwards kick them to the front again. Then do a final kick to the back while pulling the line down in front of you, and put your feet on the line.",Get some momentum with your legs in the bottom part of the bounce. As soon as you are weightless pull the line below your feet.; This trick doesn't require as much strength as you would think! It's all about getting enough momentum with your legs.; If you can't hold the bounce in the Rocket position try again with less bounce.,
10075,Reverse Rocket Mount to Double Drop Knee,,Domingo Capo,2021,https://youtu.be/7yLCyoHgUS0?t=1775,1775,1782,ROCKET,DOUBLE DROP KNEE,5,From Hanging do a Reverse Rocket Mount but land in Double Drop Knee.,,
10076,Double Drop Knee Roll to Feet,,Domingo Capo,2021,https://youtu.be/7yLCyoHgUS0?t=1767,1767,1772,DOUBLE DROP KNEE,EXPOSURE,5,From Double Drop Knee do a Double Drop Knee Roll and stand up to land in Exposure.,,
10077,Hammock Back Roll,,Guillaume Fontaine,2017,https://youtu.be/Ej2ocABoNC4?t=22785,22785,22790,BACK,KOREAN,5,Do a Hammock Roll and finish with a Back Roll in the same bounce.,,10047
10078,Half Back Roll to Shoulder Roll,,Guillaume Fontaine,2017,https://www.youtube.com/watch?v=O_E_2cB0Pcw&t=61,61,65,BACK,SHOULDER,5,Do a Half Back Roll but add a Shoulder Roll to finish the trick.,,10051;10037
10080,Front Roll from Feet,Frontflop,Guillaume Fontaine,2017,https://youtu.be/n2z3IyeQSj4?t=41,41,44,STAND,KOREAN,5,"From Standing grab the line as in a Kamikaze, but then roll over your back and land in Korean.",Thread your arm through the leash so it is not wrapped around your shoulder.,
10081,Chest Roll BS 360 Flatspin,,Ian Eisenberg,2021,https://www.youtube.com/watch?v=n2z3IyeQSj4&t=25,25,33,CHEST,CHEST,5,Do a Chest Roll followed by a BS 360 Chest Flatspin.,,
10082,Half Nasty 180 Front Sofa Roll,Mini-Cube,Ian Eisenberg,2021,https://www.youtube.com/watch?v=7yLCyoHgUS0&t=1142,1142,1147,SOFA,SOFA,5,Do a Half Nasty 180 with an additional Front Sofa Roll. The motions happen at the same time rather than one after each other.,,10213
10083,Rocket 180 Roll to Sofa Roll,Rocket Rewind Roll,Ian Eisenberg,2021,https://youtu.be/n2z3IyeQSj4?t=47,47,53,ROCKET,SOFA,6,Rocket Rewind with an additional Back Sofa Roll in the end.,,10063
10085,Backbounce Panic Roll to Feet,,Lukas Irmler,2018,https://youtu.be/Se5XNo0RSP8?t=437,437,441,BACK,EXPOSURE,6,From Backbounce go into the Panic Roll to Feet.,,10050
10086,Back Roll from Feet,Dibahia Roll (Backflop),Matheus Stoco Vidal,,https://youtu.be/Ej2ocABoNC4?t=18150,18150,18154,STAND,KOREAN,5,From standing you jump straight backwards and roll over your shoulder to land in Korean.,"Have the leash on the same side as the shoulder you roll over; it's a bit easier if you don't jump backwards, but instead roll over your back.",10047
10087,Rocket Mount to Shoulder,,Samuel Volery,2017,https://youtu.be/Se5XNo0RSP8?t=527,527,533,ROCKET,SHOULDER,6,From Rocket go up to shoulder stand.,When dropping down to Rocket already grab with the hands as you would for the Shoulderstand then you don't have to regrab.,
10088,Rocket Backflip,,Sebastian Egger,2021,https://youtu.be/9Ab1JPDJR-I?t=168,168,171,ROCKET,ROCKET,6,"In Rocket do a backflip, completely letting go of the line and landing back in Rocket.",,
10089,Side Roll over Neck,Sarah Roll,Tlaloc Moctezuma-Burns,2020,https://youtu.be/Se5XNo0RSP8?t=563,563,568,SOFA,SOFA,5,Sit in Sofa and roll to the side over your neck back to Sofa.,There are more comfortable tricks to try.,
10090,Back Chest Roll to Feet,,,,https://www.instagram.com/p/CUITT4wgvmH/,,,CHEST,STAND,4,Do a Back Chest Roll and in the end of the roll push yourself away from the line to put your front foot on.,,
10177,Full Flare from Korean,Nasty Korean,Sebastian Egger,2021,,,,KOREAN,KOREAN,6,Full Flare (see breakdancing) from Korean to Korean.,,
10201,Yisus Mount,,Leonardo Ferrari,2021,https://www.instagram.com/p/CXeLk4Qldu_/,,,YISUS,EXPOSURE,5,Hanging on the line grabbing it with both hands and having it run under your elbows and shoulders press yourself up to Exposure.,Watch out for your shoulders on this one!,
10202,Orbital to Sofa,,Ian Eisenberg,2021,,,,STAND,SOFA,5,"Like an Orbital but instead of throwing your leg over the line, put the line under your butt to# land in Sofa.",,10084
10203,Shaolin,,Ian Eisenberg,2021,,,,ROCKET,ROCKET,5,Like a Rocket Mount to Sofa but instead of landing in Sofa you pop both legs through your arms and then drop back to Rocket.,,
10214,Reverse Panic Roll to Feet,,,,,,,KOREAN,EXPOSURE,6,From Korean you do a 270 BS spin to the front and then go into a Front Sofa Roll to Feet.,,10213
10216,Reverse Flowflip to Feet,Wolf Flip to Feet,Ian Eisenberg,2022,https://www.instagram.com/p/CfrFKq2tP0m/,,,KOREAN,STAND,6,Reverse Flowflip to Feet.,,10215
10229,Shrimpflip 180 to Belly,,,,,,,ROCKET,BELLY,5,From Rocket thread your legs in between your arms and the line and let go with one hand to start the 180. Land in Belly.,,
10231,Frontroll to Feet,,,,,,,SHOULDER,STAND,6,From Shoulder push yourself forward to roll over your back and land on your Feet.,,10048
10282,Side Roll,,,,,,,SOFA,SOFA,5,From Sofa grab the line with one hand in the direction that you're rolling towards and pull on the line to initiate a sidewards roll. Roll over your lower back until you land back in Sofa.,Grabbing the line with both hands shortly before landing can help to readjust your position a bit.,
10074,Reverse Obi-Wan,,Sakalomo,,https://youtu.be/n_YEN0Yva5I?t=161,161,166,ROCKET,STAND,6,"From Rocket swing your legs up (feet first) and put one foot on the line outside of your hands. When you finish the rotation, put the second foot on and land in Exposure. ",Bring the foot that does not go to the line straight away far over the line to get your center of gravity right over the line and then put it on the line in the end of the trick.,
10079,Back Roll to Feet,,Guillaume Fontaine,2017,https://www.youtube.com/watch?v=Se5XNo0RSP8&t=662,662,666,BACK,STAND,6,"Do a Back Roll, then put your back foot on the line first, and press yourself up to put the second foot on.",,10047
10084,Orbital,,Ian Eisenberg,2020,https://www.youtube.com/watch?v=t6xPycD-JbY,,,STAND,KOREAN,5,"Grab the line with your back hand, bring it up around your body by passing it to your other hand, and finally pass your leg over the line to land in Korean.",,
10092,Hammock Roll to Feet,,Augustin Moinat,2021,,,,BACK,STAND,5,"Grab the line with one hand behind your head and the second hand below your back, do a Hammock Roll, and go to Feet.",,
10093,BS 270 Can of Soup,Can of Bisque,Davis Hermes,2021,https://youtu.be/VP49hErTqM0?t=356,356,362,SOUP,EXPOSURE,6,Do a Can of Soup followed by a BS 270 spin landing in Exposure.,,10066
10094,Exposure Orbital to Sofa,Exporbital,Ian Eisenberg,2021,https://www.youtube.com/watch?v=2ykEngQRgKo&t=6,6,16,EXPOSURE,SOFA,5,Orbital to Sofa but starting in Exposure.,,10084
10095,Antihero from Feet,Mini-Eisenvader,Ian Eisenberg,2021,https://youtu.be/7yLCyoHgUS0?t=1437,1437,1442,EXPOSURE,SOFA,7,From Exposure you grab the line with one hand and roll forward. As soon as you are under the line you perform an Antihero landing in Sofa.,,10039
10096,180 to Orbital,,Ian Eisenberg,2021,https://youtu.be/A8O3iGYGPPk?t=146,146,154,STAND,KOREAN,6,Do a 180 spin followed by an Orbital.,,10084
10097,Rocket Mount 180,,Ian Eisenberg,2020,https://youtu.be/dG9sJvKjg6E?t=285,285,293,ROCKET,EXPOSURE,6,"Start as you would for the Rocket Mount, and then half way up you push with one hand and pull with the other to initiate a 180 spin, landing in Exposure.",The movement in the end is comparable to the Sofa 360 to Feet.,10067
10098,Sick Nasty Double Roll,,Ian Eisenberg,2020,https://youtu.be/qLEnzTtvTcA?t=21,21,26,SOFA,SOFA,5,Sick Nasty Roll with an additional Back Sofa Roll in the same bounce.,,10068
10099,Sofa 360 Double Roll,,Justin Wagers,2020,https://youtu.be/hsALSrUdryU?t=134,134,139,SOFA,SOFA,5,Do a Sofa Roll 360 with an additional Back Sofa Roll in the end.,You have to be fast with the regrab.,10022
10100,BS 180 Front Korean Roll to Feet,Fire Flip,Salomé Cholet,2021,https://youtu.be/HecUpHXRpDw?t=302,302,315,KOREAN,STAND,6,Do a Mini-Fireflip to Feet.,,10209
10101,Back Belly Roll to Feet,,,,https://www.youtube.com/watch?v=7yLCyoHgUS0&t=723,723,729,BELLY,EXPOSURE,5,Do a Back Belly Roll to Feet.,,
10102,Flowflip to Feet,,,,https://www.youtube.com/watch?v=kn15JZJOuAg,,,KOREAN,EXPOSURE,5,Do a Flowflip to Feet. ,During the flip get your far foot on the line. At the end of the flip get your second foot up on the line; A lot of people do it landing in Exposure.,10015
10103,Backbounce Richy Roll to Feet,,,,https://www.youtube.com/watch?v=uuFlRIMmP8M&t=260,260,264,BACK,EXPOSURE,5,From Backbounce perform a Richy Roll but land it to Feet.,,10226;10227
10104,Shoulder Roll to Feet,,,,https://www.youtube.com/watch?v=7CZuU59KY_c&t=71,71,78,SHOULDER,EXPOSURE,5,From Shoulderstand roll to one side and get your feet on the line. Land in Exposure.,,10051
10105,Panic Roll to Shoulder,,,,https://youtu.be/uOuqykzwN7w?t=48,48,58,SOFA,SHOULDER,5,Do the Panic Roll but instead of landing in Chest you go into Shoulderstand.,Regrab with one hand to land comfortably in Shoulderstand.,10000
10119,Yoda Roll,,Samuel Volery,2016,https://www.youtube.com/watch?v=DgVLWsChXFM,,,EXPOSURE,EXPOSURE,6,From Exposure grab the line with both hands and roll around the line landing back in Exposure.,Try to wait a bit after hitting the bottom of the bounce before you start with the trick. If you start too early you will kill the bounce.,10199
10120,Back Yoda Roll,,Samuel Volery,2017,https://youtu.be/QJzX6gaYQoM?t=34,34,41,EXPOSURE,EXPOSURE,6,From Exposure grab the line with both hands and roll around the line backwards landing back in Exposure.,Try to wait a bit after hitting the bottom of the bounce before you start with the trick. If you start too early you will kill the bounce.,10200
10122,Barrel Roll,,,,https://www.youtube.com/watch?v=dG9sJvKjg6E&t=396,396,402,STAND,STAND,6,From your normal stance grab the line with both hands and roll around the line landing back in the starting position.,,10066
10123,Back Barrel Roll,,,,https://www.youtube.com/watch?v=dG9sJvKjg6E&t=396,396,402,STAND,STAND,6,From your normal stance grab the line with both hands and roll around the line backwards landing back in the starting position.,,10169
10195,Reverse Whatever,,Sebastian Egger,2021,https://youtu.be/Ej2ocABoNC4?t=23482,23482,23490,LEASH,EXPOSURE,7,Drop into the leash and on the way up climb the leash and finish with a Reverse Obi-Wan.,Amazing leash fall saving trick.,10074
10217,Sick Nasty Roll from Feet,,Ian Eisenberg,2021,https://youtu.be/aAq4Tf8naOM?t=80,80,84,EXPOSURE,SOFA,6,Sick Nasty Roll but starting in Exposure.,,10068
10219,Korean 540 to Feet,Flower,Tim Odermatt,2021,https://youtu.be/aAq4Tf8naOM?t=131,131,135,KOREAN,STAND,6,Like a normal Flow to Feet but adding a 180 at the end.,,10224
10106,Double Hammock Roll from Feet,Spaghetti Roll,Augustin Moinat,2021,,,,STAND,BACK,6,Do a Hammock Roll from Feet and add an extra Hammock Roll at the end.,,10023
10107,Double Sofa Roll to Feet,Tamatta Roll,Axel Weber,2021,https://youtu.be/9Ab1JPDJR-I?t=250,250,254,SOFA,EXPOSURE,6,Double Sofa Roll landing in Exposure.,,10199
10109,Sick Nasty 360,Tre Nasty,Ian Eisenberg,2021,https://youtu.be/wHPNMiKrHsQ?t=44,44,63,SOFA,SOFA,6,Start with the motion of a Half Nasty 180 but pass your legs over the line once more and keep spinning to do a full 360 landing back in the starting position.,,10044
10111,Chest Roll 180 Flatspin to Feet,,Ian Eisenberg,2021,https://www.youtube.com/watch?v=n2z3IyeQSj4&t=16,16,23,CHEST,EXPOSURE,6,Do a Chest Roll followed by a 180 Chest Flatspin to Feet.,,
10112,Shapeshifter,,Ian Eisenberg,2021,https://www.youtube.com/watch?v=QrUyUx8oJUY,,,EXPOSURE,ROCKET,6,From Exposure do a front flip off the line and catch the line to land in Rocket.,,
10113,Rocket Mount Side Roll to Sofa,,Ian Eisenberg,2021,https://www.youtube.com/watch?v=7yLCyoHgUS0&t=1082,1082,1091,ROCKET,SOFA,6,From Rocket Mount do a Side Roll with the axis of rotation perpendicular to the line and land in Sofa.,Flip one of your hands to allow for a better initiation of the momentum.,
10114,Korean Roll from Feet to Feet,Sushi Roll,Ian Eisenberg,2021,https://youtu.be/Ab2gW1rv5e8?t=16,16,20,STAND,STAND,6,Do a Korean Roll but starting from Feet and landing to Feet.,,10041
10115,180 Orbital to Feet,Sakalorbital,Ian Eisenberg,2020,https://youtu.be/Ab2gW1rv5e8?t=69,69,74,STAND,EXPOSURE,7,"Grab the line with one hand, bring it around your body by passing it to your other hand above your head. Put the line back under your feet to land in Exposure.",,10084
10116,Sick Nasty 360 to Chest,Tre Nasty to Chest,Ian Eisenberg,2021,https://youtu.be/eP2pBpKv4wI?t=39,39,44,SOFA,CHEST,6,Tre Nasty landing in Chest.,,10109
10117,Freak Nasty to Feet,,Ian Eisenberg,2020,https://youtu.be/T27UrrWAr7A?t=36,36,53,SOFA,EXPOSURE,6,Do a Freak Nasty landing in Exposure.,,10065
10118,540 Spin,,Joshua Leupolz,2021,https://youtu.be/qUxUNfgvoPs?t=46,46,49,STAND,STAND,6,Spin 540 on the line in a standing position.,,10228
10121,Reverse Rocket Mount,,Samuel Volery,2019,https://youtu.be/uOuqykzwN7w?t=171,171,188,ROCKET,EXPOSURE,6,From Rocket swing your legs up (feet first) and put both feet on the line inside of your hands and land in Exposure. ,Sam and Ian have quite different techniques for this trick. Try both and see which one suits you (or do your own variation of course).,
10124,Almighty Flip,,Axel Weber,2020,https://youtu.be/jIBjYEMRhrQ,,,EXPOSURE,EXPOSURE,7,From Exposure do a front flip while hooking one foot under the line and putting it back on the line for the landing.,After 270 deg of rotation try to pull the line under yourself with your feet.,10119
10136,Barrel Almighty Flip,,Justin Wagers,2020,https://youtu.be/hsALSrUdryU?t=62,62,66,STAND,STAND,7,Almighty flip but from normal stance.,,10122
10138,Back Barrel Almighty Flip,,Justin Wagers,2020,https://youtu.be/Se5XNo0RSP8?t=426,426,430,STAND,STAND,7,Like the Barrel Almighty Flip but flipping backside.,,10123
10143,Back Almighty Flip,,Sebastian Egger,2020,https://youtu.be/jIBjYEMRhrQ,,,EXPOSURE,EXPOSURE,7,From Exposure do a back flip while hooking one foot under the line and putting it back on the line for the landing.,First lean back and then kick/hook the line.,10120
10170,Back Korean Roll 360 to Chest,Despedido,Sakalomo,2021,https://www.youtube.com/watch?v=7yLCyoHgUS0&t=1036,1036,1040,KOREAN,CHEST,5,"Start with a Back Korean Roll during which you are leaning forward, move your legs above the line to transition into a 360, land in Korean.",,
10174,Shrimp Double Flip,Kung Pao,Ian Eisenberg,2021,https://www.instagram.com/p/CXPSK-BKQAg/,,,ROCKET,ROCKET,999,Do a Shrimpflip and in the same bounce another roll backwards around the line.,,10060;10121
10176,Back No Soup,,Tim Odermatt,2021,https://www.instagram.com/p/CVvIbn3lFqU/,,,SOUP,EXPOSURE,7,"A Can of Soup without hands, basically a Back Almighty starting from Soup.","Throw your hands in the air at the bottom of the bounce, it will allow you to gain more momentum to finish the rotation.",10143
10194,Leash to Feet,Whatever,Enzo Fuchs,2021,https://www.instagram.com/p/CRyXVw0ISbI/,,,LEASH,EXPOSURE,7,Drop into the leash and on the way up climb the leash and finish with a Rocket Mount.,,10073
10196,Sick Nasty from Feet to Feet,,Enzo Fuchs,2021,https://www.instagram.com/p/CWQrmuTAwNl/,,,EXPOSURE,EXPOSURE,6,Sick Nasty from Feet to Feet.,,10044;10072
10212,Back Roll from Chest to Feet,Frog Flip,Ian Eisenberg,2022,https://www.instagram.com/p/CYPPtWFvkIg/,,,CHEST,STAND,7,From Chest you push off the line with both hands to get into a Back Roll to Feet.,,
10236,Underflip to Feet,Fireball,Cesare Bellamoli,2022,https://youtu.be/eUguTccJblI?t=45,,,KOREAN,EXPOSURE,999,"From Korean, do a BS 270 spin and finish with a Back Belly Roll to Feet.",,
10110,Tre Nasty Roll,Tre Flip,Ian Eisenberg,2021,https://www.instagram.com/p/CUayzIYg49i/,,,SOFA,SOFA,7,Start with the motion of a Half Nasty 180 but pass your legs over the line once more and keep spinning to do a full 360 and then add a roll around the line to land back in the starting position.,,10109
10125,No Foot Almighty Flip,High'N'Mighty,Ian Eisenberg,2021,https://www.instagram.com/p/CVYpkmVg2FY/,,,STAND,STAND,7,Barrel Front Almighty Flip but instead of hooking the line with your foot you press the line against your leg.,,10124
10126,180 Back Roll from Feet,180 Backflop,Ian Eisenberg,2021,https://www.youtube.com/watch?v=A8O3iGYGPPk&t=135,135,142,STAND,KOREAN,6,Do a 180 and then do a Backflop.,,10086
10127,NH Panic Roll to Feet,Panic Attack,Ian Eisenberg,2021,https://www.youtube.com/watch?v=7yLCyoHgUS0&t=1355,1355,1364,SOFA,EXPOSURE,7,You do a Panic Roll to Feet but don't use your hands to hold the line. Instead use your foot to hook the line and go to Feet.,,10050
10128,Shrimpflip 180 to Feet,King Prawn,Ian Eisenberg,2021,https://youtu.be/7yLCyoHgUS0?t=1560,1560,1574,ROCKET,EXPOSURE,7,Do a Shrimpflip 180 but then go to Feet.,,10229
10129,180 Front Roll from Feet,180 Frontflop,Ian Eisenberg,2021,https://youtu.be/A8O3iGYGPPk?t=116,116,132,STAND,KOREAN,6,From Standing you turn 180 and do a Frontflop.,,10080
10130,360 Orbital to Feet,,Ian Eisenberg,2021,https://youtu.be/A8O3iGYGPPk?t=175,175,192,STAND,STAND,8,Orbital to Feet but with a 360 spin.,,10115
10132,Antihero to Feet,Darth Vader,Ian Eisenberg,2021,https://www.youtube.com/watch?v=V0fMaONFvVY,,,ROCKET,EXPOSURE,7,Like an Antihero but landing in Exposure.,,10039
10133,90 to Yoda Roll,Adrenaline Roll,Ian Eisenberg,2020,https://youtu.be/qLEnzTtvTcA?t=38,38,42,STAND,EXPOSURE,6,Do a 90 with restepping and go into a Yoda Roll.,,10050
10134,Han Solo,,Jim Galli,2020,https://www.youtube.com/watch?v=dG9sJvKjg6E&t=323,323,327,EXPOSURE,EXPOSURE,6,Almighty Flip but instead of hooking the line with your foot you grab and pull on the leash.,,10119
10135,Backbounce Panic Roll 180 to Feet,Backbounce Nirvana,Justin Wagers,2021,https://www.instagram.com/p/CSW1c4Li76j/,,,BACK,EXPOSURE,7,Nirvana from Backbounce.,,10140
10137,Panic Double Roll to Feet,,Justin Wagers,2021,https://youtu.be/RDVaUFdqMmE?t=261,261,266,SOFA,EXPOSURE,7,Panic Roll with an additional roll landing to Feet.,,10050
10139,Double Can of Soup,,Justin Wagers,2019,https://youtu.be/rWqH_51ztQA?t=6977,6977,6981,SOUP,STAND,7,From Soup do a double roll and land on your feet in normal stance.,,10066
10140,Sofa Roll 360 to Feet,Nirvana,Salomé Cholet,2021,https://youtu.be/7yLCyoHgUS0?t=580,580,594,SOFA,EXPOSURE,7,Do a Sofa Roll 360 and land in Exposure.,,10022;10069
10141,FS 360 Rocket Mount,,Sebastian Egger,2021,https://www.instagram.com/p/CPgJRJHK777/,,,ROCKET,EXPOSURE,7,Rocket Mount with a 360.,First spin a little bit into the opposite direction to then explode out the way you really want to spin.; Try to avoid doing a Rocket Mount 180 and then restep with your feet but go for the 360 right away.,10097
10142,Sofa 540 to Feet,,Sebastian Egger,2021,https://www.instagram.com/p/CPgJRJHK777/,,,SOFA,EXPOSURE,7,Like a Sofa 360 to Feet but with a late 180.,Try to not do the 360 and then restep to get the 540 but instead go for the 540 directly.,10069
10144,Switch 270 Yoda Roll Fake 90,Flowflip from Feet to Feet,Sebastian Egger,2021,,,,STAND,STAND,7,From switch do 270 spin and go into a Yoda Roll and finish by turning to normal stance.,Either start or land in switch.,10171
10145,Butter Roll to Feet,The Tesseract,Ian Eisenberg,2021,https://www.instagram.com/p/CVhgrM6B6jd/,,,SOFA,EXPOSURE,7,"Start by doing the Butter and roll to your back, put your feet on the line to land in Expo.",,10230
10171,180 Front Yoda Roll,,Ian Eisenberg,2021,https://youtu.be/Ab2gW1rv5e8?t=22,22,33,EXPOSURE,EXPOSURE,7,From Exposure do a 180 and during the spin go into the Yoda Roll.,,10119
10173,BS 270 Back Yoda Roll,Dojo Roll,Ian Eisenberg,2021,https://youtu.be/BOGMXJsXWCE?t=31,31,43,STAND,EXPOSURE,7,Turn 180 to your BS and go into a Back Yoda Roll finishing the last 90 degrees of spin.,,10120;10145
10178,Almighty from Sofa,Dirty Sofa,Tim Odermatt,2021,,,,SOFA,EXPOSURE,7,"Start in Sofa, then bring one foot up to the line to hook it and go for an Almighty Flip.",,10124
10193,Double Shoulder Roll to Feet,,Enzo Fuchs,2020,https://www.instagram.com/p/CFKdxdlq9yd/,,,SHOULDER,EXPOSURE,7,Double Shoulder Roll landing in Exposure.,,
10197,Front Yoda Rewind,,Sebastian Egger,2021,https://youtu.be/aAq4Tf8naOM?t=135,135,139,EXPOSURE,EXPOSURE,8,It's almost a Front Yoda Roll and a Back Yoda Roll in the same bounce. Start at the very bottom of the bounce with a Front Yoda Roll so the line snaps up and after around three quarters of rotation you have some resistance of the line to push off of into the Back Yoda Roll. ,Start a lot earlier than you would for most tricks.,
10198,Back Yoda Rewind,,Tim Odermatt,2021,,,,EXPOSURE,EXPOSURE,8,It's almost a Back Yoda Roll and a Front Yoda Roll in the same bounce. Start at the very bottom of the bounce with a Back Yoda Roll so the line snaps up and after around three quarters of rotation you have some resistance of the line to push off of into the Front Yoda Roll. ,Start a lot earlier than you would for most tricks.,
10207,Tre Nasty to Feet,,Ian Eisenberg,2021,,,,SOFA,STAND,999,Tre Nasty landing to Feet.,,10109
10218,360 Expo Orbital to Feet,Cosmonaut,Ian Eisenberg,2021,https://youtu.be/lzz9jvtYpi0?t=567,567,572,EXPOSURE,EXPOSURE,8,Expoorbital to Feet with a 360 spin.,,10115
10146,Hammock Roll from Feet to Feet,Lasagna Roll,Augustin Moinat,2021,https://youtu.be/aAq4Tf8naOM?t=139,139,144,STAND,STAND,8,Hammock Roll starting from Feet and going directly back to Feet.,,10023;10092
10147,Panic Roll 180 from Feet to Feet,Total Nirvana,Sakalomo,2021,https://youtu.be/HecUpHXRpDw?t=55,55,68,EXPOSURE,EXPOSURE,8,Basically a Sofa Roll 360 from Feet to Feet.,,10140
10148,Back Roll from Feet to Feet,Backflip,Ian Eisenberg,2021,https://youtu.be/Ej2ocABoNC4?t=18588,18588,18593,STAND,STAND,8,It is a Back Roll from Feet to Feet.,,10079;10086
10149,Rocket Front Belly Roll to Feet,Supersonic Mount,Ian Eisenberg,2020,https://www.youtube.com/watch?v=r5rwYkvnbco,,,ROCKET,EXPOSURE,7,From Rocket get a lot of momentum with your feet and do one roll forward around the line and land in Exposure.,,10056
10150,Double Back Yoda Roll,Back Turtle Roll,Ian Eisenberg,2020,https://www.youtube.com/watch?v=RerW2T7edVA,,,EXPOSURE,EXPOSURE,7,Two Back Yoda Rolls in one bounce.,,10120
10151,Sick Nasty Roll to Feet,Darkside Roll,Ian Eisenberg,2020,https://youtu.be/Ab2gW1rv5e8?t=79,79,91,SOFA,EXPOSURE,7,Do a Sick Nasty Roll but instead of swinging both your legs over the line again put one foot on the line and keep the other one behind the line. Then put the second foot on and stick the trick.,,10068
10152,180 Darth Vader,,Ian Eisenberg,2021,https://youtu.be/HecUpHXRpDw?t=218,218,234,ROCKET,EXPOSURE,8,Darth Vader with a 180.,,10074
10153,180 Almighty Flip,,Ian Eisenberg,2021,https://youtu.be/n2z3IyeQSj4?t=88,88,105,EXPOSURE,EXPOSURE,8,Do a 180 and then go into a Front Almighty Flip.,,10124
10154,Double Barrel Roll,,Justin Wagers,2021,https://www.youtube.com/watch?v=VP49hErTqM0&t=415,415,419,STAND,STAND,7,Double Barrel Roll.,,10139
10155,Frontroll from Feet to Feet,Frontflip (Chrysalis),Nick Day,2021,https://www.youtube.com/watch?v=8fqUe9ZQvAc,,,STAND,STAND,8,Front Roll from Feet to Feet.,Longer lines allow for more time to execute the trick.,10080;10231
10156,Double Yoda Roll,Turtle Roll,Pablo Signoret,,https://www.youtube.com/watch?v=VP49hErTqM0&t=420,420,423,EXPOSURE,EXPOSURE,7,Two Yoda Rolls in one bounce.,,10107
10157,Fake 360 Almighty Flip,,Sebastian Egger,2021,https://www.instagram.com/p/COPXx5vtOBy/,,,STAND,STAND,8,"Starting in switch do a 270 spin, go into a Front Almighty Flip and in the end turn 90 to look back at the same anchor as where you started.",,10153
10158,FS 360 Barrel Roll,Overflow,Tim Odermatt,2021,https://www.instagram.com/p/CSHcZfUFG9H/,,,STAND,STAND,999,From your regular stance do a frontside 270 and roll around the line like you would for a Flowflip. Try to land back in your normal stance and not in Exposure.,,10171
10175,Barrel late Orbital 180,,Justin Wagers,2021,https://www.instagram.com/p/CXJSAepFj4L/,,,STAND,CHEST,999,Start with a Barrel Roll and then add an Orbital 180 in the same bounce.,You gotta be quick for this one.,10122;10206
10220,Half Nasty 180 Front Sofa Roll to Feet,Rubik's Cube,Ian Eisenberg,2021,https://www.instagram.com/p/CPWrEFhKBUm/,,,SOFA,EXPOSURE,7,It's a Half Nasty 180 with a Front Sofa Roll landing in Exposure.,,10214
10159,Makako to Feet,,Sakalomo,2021,https://youtu.be/rWqH_51ztQA?t=5633,5633,5640,NEVERMIND,EXPOSURE,999,Makako landing in Exposure.,,10052
10160,Despedido to Feet,,Sakalomo,2021,https://youtu.be/HecUpHXRpDw?t=162,162,178,KOREAN,EXPOSURE,999,Despedido landing in Exposure,,10170
10161,180 Super Sonic Mount,,Ian Eisenberg,2021,https://youtu.be/HecUpHXRpDw?t=249,249,265,ROCKET,EXPOSURE,8,It's a Super Sonic late 180 or Rocket Rewind to Feet.,,10149;10140
10162,360 Almighty Flip,,Ian Eisenberg,2021,https://youtu.be/HecUpHXRpDw?t=367,367,380,STAND,STAND,8,360 Almighty Flip.,,10153
10163,Reverse Super Sonic Mount,,Samuel Volery,2021,https://www.youtube.com/watch?v=EntnbHe_biY,,,ROCKET,EXPOSURE,999,From Rocket get a lot of momentum with your feet and do one roll backwards around the line and land in Exposure.,,10101;10121
10172,Shapeshifter to Feet,Ninja Shifta,Enzo Fuchs,2021,https://www.instagram.com/p/CXOfVZGgZ7b/,,,EXPOSURE,EXPOSURE,8,Shapeshifter landing to feet.,,10112
10208,Kung Pao to Feet,Shrimpzilla,Ian Eisenberg,2021,https://www.instagram.com/p/CXXU9U7KvZ7/,,,ROCKET,EXPOSURE,999,Shrimpflip to Reverse Rocket Mount.,,10174
10232,Half-Nasty 360 Roll to Feet,Megaminx,Ian Eisenberg,2022,https://www.instagram.com/p/CZQI4Nur_XQ/,,,SOFA,EXPOSURE,999,"Start like you would for the Half-Nasty 180, but then keep spinning to do a 360 by regrabing your hands and finish Reverse Obi-Wan.",,10220
10233,180 Backflip,,Oscar Defoor,2022,https://www.instagram.com/p/CadBn6CjXqM/,,,STAND,EXPOSURE,999,"Start in regular position, rotate 180° backside and do a backflip starting from switch position. Roll over the same shoulder as the normal backflip.",Get the 180° backflop as solid as possible first!,10148;10126
10234,Double Back Roll from Feet,Double Dibahia,Ian Eisenberg,2022,https://www.instagram.com/p/CZh3qZata-5/,,,STAND,KOREAN,999,Double Backroll from feet.,Protecting your arm from leashburns could be beneficial.,10086
10235,Double Back Yoda Roll 180,Yodermatt,Tim Odermatt,2022,https://www.instagram.com/p/Caf2ldqgtLc/,,,EXPOSURE,EXPOSURE,9,Back Yoda Roll to Back Yoda Roll 180 in one bounce.,,10150
10164,Triple Back Yoda Roll,,Davis Hermes,2021,https://www.instagram.com/p/CUNMWEgAGP4/,,,EXPOSURE,EXPOSURE,9,Three Back Yoda Rolls in one bounce.,,10150
10165,Barrel Almighty Flip to Barrel Roll,Holy Grail,Davis Hermes,2021,https://youtu.be/UdG4DNI0SNk?t=92,92,97,STAND,STAND,9,Start by doing a Barrel Almighty Flip and go for a second roll by grabbing the line and doing a Barrel Roll.,,10154
10166,Darth Vader from Feet,Eisenvader,Ian Eisenberg,2021,https://youtu.be/HecUpHXRpDw?t=436,436,452,EXPOSURE,EXPOSURE,9,Start in Expo and roll down until you are in Rocket. Then do a Darth Vader.,,10132;10095
10167,Double Back Almighty Flip,,Sebastian Egger,2021,https://youtu.be/HecUpHXRpDw?t=547,547,567,EXPOSURE,EXPOSURE,9,Double Back Almighty Flip.,Do the first one laid out and tuck for the second one to get good momentum.; Try to get the hook at your ankle. If the line is near your toes it's hard to pull it around for the second roll.,10150;10143
10168,Double Front Almighty Flip,,Sebastian Egger,2021,https://youtu.be/HecUpHXRpDw?t=780,780,793,EXPOSURE,EXPOSURE,9,Double Front Almighty Flip.,Stay open for the first one and tuck for the second one to get good momentum.,10156;10124
10238,Front Sofa Roll Rewind to Sick Nasty Double Roll,Double Boomerang,Ian Eisenberg,2022,https://youtu.be/rWqH_51ztQA?t=6940,6940,6946,SOFA,SOFA,999,Start early with a Lightside Roll and use the resistance in the line to finish with a Double Sick Nasty Roll.,,
10239,Shrimpflip 360 to Feet,Shrimp Cocktail,Ian Eisenberg,2022,https://www.instagram.com/p/CbV9q1_p8DI/,,,ROCKET,EXPOSURE,8,"Start with a Shrimpflip, let go with one hand to initiate the 360 spin and land in Exposure.",,
10241,360 from Feet to Korean,Downward Spiral,Ian Eisenberg,2022,https://www.instagram.com/p/Cck9B16DcDi/,,,STAND,KOREAN,5,"Kick your back leg to the front, initiate a 360 with your upper body, and bring your front leg around to land in Korean.",,
10242,OH Back Handspring to Korean,Capoeira Flop,Ian Eisenberg,2022,https://www.instagram.com/p/Cck9B16DcDi/,,,STAND,KOREAN,999,Do a OH Back Handspring to Korean.,,
10243,Front Sofa Roll Rewind to Sick Nasty Roll,Boomerang,Ian Eisenberg,2022,https://www.instagram.com/p/Cck9B16DcDi/,,,SOFA,SOFA,6,Start early with a Lightside Roll and use the resistance in the line to finish with a Sick Nasty Roll.,,
10244,Sushi Backflop,,Ian Eisenberg,2022,https://www.instagram.com/p/CdsGGZrvNJ2/,,,STAND,KOREAN,7,Start with a early Sushi and go into the Backflop at the top of the bounce.,,
10246,Shrimp Mount,,Ian Eisenberg,2022,https://www.instagram.com/p/Cd7NRJeNEAa/,,,ROCKET,EXPOSURE,5,"From Rocket, stay below the line, pull just your legs up and kick in between the arms with extended legs. With the momentum from the leg kick, bring your body above the line, tuck your legs and land in Exposure.",,
10247,Double Drop Knee Almighty,,Ian Eisenberg,2022,https://www.instagram.com/p/CeVEh4DDYle/,,,DOUBLE DROP KNEE,EXPOSURE,999,Almighty from DDK.,,
10248,Boomerang to Feet,Bangarang,Ian Eisenberg,2022,https://www.instagram.com/p/CeVEh4DDYle/,,,SOFA,EXPOSURE,8,Boomerang to Feet.,,
10249,No Hands Back Panic Roll to Feet,Back Panic Attack,Ian Eisenberg,2022,https://www.instagram.com/p/Cfczh8IpvK4/,,,SOFA,EXPOSURE,7,"From Sofa, bring your back leg over the line (like a heel hook), initiate a roll backwards and immediately hook with your front foot, finish the roll and put your feet back on the line to land the trick.",,
10250,Front Sofa Roll Rewind to Mini-Cube,Boomerang 180,Ian Eisenberg,2022,https://www.instagram.com/p/CgUkGA0uVlA/,,,SOFA,SOFA,7,"This trick starts with an early Front Sofa Roll for which you grab both hands on your side (the Sick Nasty way). During the Front Sofa Roll, pass your legs over the line. Then use the resistance of the line to rewind your rolling direction and finish with the second half of a Mini-Cube.",,
10251,Reverse Rocket Mount 360 ,,Ian Eisenberg,2022,https://www.instagram.com/p/CgUkGA0uVlA/,,,ROCKET,EXPOSURE,999,We haven't figured out yet what's going on here. Look at the video and help us by updating the description.,,
10252,Sushi Backflip,Sushi-Flip,Ian Eisenberg,2022,https://www.instagram.com/p/Cg8_eXWLmXw/,,,STAND,STAND,9,Start with an early Sushi and then do a Backflip at the top of the bounce.,,
10253,NH Backflip,,Ian Eisenberg,2022,https://www.instagram.com/p/Cg_eTDJLsZ6/,,,STAND,STAND,9,Do a Backflip without grabing the line.,,
10255,Batman,,Ian Eisenberg,2022,https://www.instagram.com/p/ChsA7RvrV7m/,,,ROCKET,ROCKET,5,"From Rocket, swing your legs to the side, hook the line with both feet, let go of your hands to ""hang"" on the line at the top of the bounce, finish the sidewards motion with your upper body and regrap with the hands. Let your feet go off the line to finish back in Rocket.",,
10256,Shark Bite,,Ian Eisenberg,2022,https://www.instagram.com/p/ChsA7RvrV7m/,,,ROCKET,ROCKET,4,"From Rocket, bite the line at the top of the bounce and let go of your hands at the same time. Regrab with your hands to finish the trick in Rocket at the bottom of the bounce.",,
10257,Antihero to Sofa Roll to Feet,Double Darth Vader,Ian Eisenberg,2022,https://www.instagram.com/p/ChsjejWLu8d/,,,ROCKET,EXPOSURE,9,Do an Antihero followed by a Sofa Roll to Feet in the same bounce.,,
10258,Darkside Almighty,All-Nasty,Ian Eisenberg,2022,https://www.instagram.com/p/Chxgwo6s6g_/,,,SOFA,EXPOSURE,8,"Start as you would for the Darkside Roll, but instead of putting the first foot on the line, hook it like for a Back Almighty, put the second foot on the line, let go of your hands and finish as you would for a Back Almighty.",,
10259,540 Rocket to Sofa,,Ian Eisenberg,2022,https://www.instagram.com/p/Ch11yrdsUEG/,,,ROCKET,SOFA,7,"From Rocket, pull yourself up half-way, then initiate the spin and land in Sofa.",,
10260,360 Back Almighty,,Ian Eisenberg,2022,https://www.instagram.com/p/Ch99aJdpyUo/,,,STAND,STAND,8,"Do a FS 270 spin, followed by a Back Almighty and spin another 90 degrees to finish looking back at the anchor. ",,
10261,Orbital to Double Drop Knee,,Ian Eisenberg,2022,https://www.instagram.com/p/Cjkb1LXrFci/,,,STAND,DOUBLE DROP KNEE,999,Orbital to DDK.,,
10262,Shrimpflip 180 to Antihero,Shrimpy Hero,Justin Wagers,2022,https://www.instagram.com/p/CaPmmmsl1e3/,,,ROCKET,SOFA,7,"Start with a Shrimpflip, let go with one hand to initiate the 180 and finish with an Antihero, landing in Sofa.",,
10263,Backbounce Panic Attack,Back Attack,Justin Wagers,2022,https://www.instagram.com/p/Ce3cq4OIs0l/,,,BACK,EXPOSURE,8,NH Panic Roll to feet starting from Backbounce.,,
10264,Holy Back No Soup,,Justin Wagers,2022,https://www.instagram.com/p/CgMeLKqogmm/,,,SOUP,EXPOSURE,8,NH Back Can of Soup to Back Yoda Roll in one bounce.,,
10265,360 Darth Vader,,Justin Wagers,2022,https://www.instagram.com/p/Cgb_ScXIF86/,,,ROCKET,EXPOSURE,9,Do a 360 and a Darth Vader at the same time.,,
10266,Back Holy Grail,,Justin Wagers,2022,https://www.instagram.com/p/Cgt9fIHIsrr/,,,EXPOSURE,EXPOSURE,9,Do a Back Almighty and a Back Yoda Roll in one bounce.,,
10267,Leash Orbital,Lando,Davis Hermes,2022,https://www.instagram.com/p/CgrrMmhgxhF/,,,STAND,KOREAN,7,"Do an Orbital, but grabing the leash instead of the line.",,
10269,Darth Vader from Yisus,Resurrección,Gon Caturelli,2022,https://www.instagram.com/p/CZ5RlXfjAnA/,,,YISUS,EXPOSURE,999,We haven't figured out yet what's going on here. Look at the video and help us by updating the description.,,
10270,Antihero from Yisus,Anticristo,Gon Caturelli,2022,https://www.instagram.com/p/CZPRbnNKCZ4/,,,YISUS,SOFA,999,We haven't figured out yet what's going on here. Look at the video and help us by updating the description.,,
10272,Orbital from Chest to Feet,Onda,Cesare Bellamoli,2022,https://youtu.be/eUguTccJblI?t=23,,,CHEST,EXPOSURE,6,We haven't figured out yet what's going on here. Look at the video and help us by updating the description.,,
10273,90 Korean Roll to Expo,FireFly,Samuel Volery,2021,https://www.instagram.com/p/CVQIDtpAbme/,,,KOREAN,EXPOSURE,5,"Start the same way as you would for the Fireflip, but go directly to Expo without doing the 180.",,
10274,Sick Nasty to Yisus,Nasty Christo,Gon Caturelli,2022,https://www.instagram.com/p/CjGFSHejhqn/,,,SOFA,YISUS,999,We haven't figured out yet what's going on here. Look at the video and help us by updating the description.,,
10276,Makako 180 to Feet,Darthkako,Sakalomo,,https://youtu.be/Ej2ocABoNC4?t=21781,21781,21788,NEVERMIND,EXPOSURE,999,"From Nevermind start with the normal Makako motion but as soon as you regrab the line with your hands, do an additional 180 before coming back to Exposure. The last part of the trick is like a Darth Vader, hence the name.",,
10277,Fake 180 Barrel Roll,,Samuel Volery,,https://youtu.be/rWqH_51ztQA?t=11530,11530,11535,STAND,STAND,7,This is a 180 Barrel Roll without restepping. This means you either start or land the trick in your switch stance.,,
10283,Orbital to Feet,,,,https://www.instagram.com/p/CLowqcjlipw/,,,STAND,STAND,7,On the way up in the bounce grab the line with one hand and bring it over your head. From there grab the line with your other hand and bring it back down to put your feet on.,,
10284,Flow to Feet,,,,,,,KOREAN,STAND,5,From Korean you grab the line with both hands behind you and then swing your far leg over the line. From there aim to land on the line with both feet to finish the trick.,,`;

// increase this manualy if you update the predefinedCombos
export const predefinedCombosVersion = 5;
// predefinedCombos have to have an id above 10000
export const predefinedCombos = `id,name,tricks,minDiff,maxDiff,avgDiff,totalDiff,numberOfTricks,establishedBy,yearEstablished,linkToVideo,comments,stickFrequency
10000,Axel's standard combo end,10103;10119,6,7,6.5,13,2,Axel Weber,2020,,stick it,0
10001,Ian's classic,10202;10082;10068;10199;10119,4,7,5,25,5,Ian Eisenberg,2021,,,0
10002,Ian's power combo,10132;10119;10120,7,8,7.33,22,3,Ian Eisenberg,2021,,,0
10003,Ian's super power combo,10149;10143;10132;10119,7,9,8,32,4,Ian Eisenberg,2022,https://www.instagram.com/p/CY7KfMWLbB1/,,0
10004,Ian's rocket combo,10203;10060;10062;10204;10205,4,5,4.2,21,5,Ian Eisenberg,2021,,,0
10005,David's favorite,10186;10124;10115;10119,0,8,5.5,22,4,David Palomo,2021,,,0
10006,Deb's favorite #1,10052;10070;10119,4,7,5,15,3,Deborah Casimiro,2021,,,0
10007,Deb's favorite #2,10206;10209;10120,3,7,4.66,14,3,Deborah Casimiro,2021,,,0
10008,Salomé's favorite #1,10221;10036;10067;10122,3,7,4.5,18,4,Salomé Cholet,2021,,,0
10009,Salomé's favorite #2,10222;10050;10122,2,7,4.33,13,3,Salomé Cholet,2021,,,0
10010,Can of Barrel Soup,10086;10066;10122,4,7,5.33,16,3,Justin Wagers,2021,,,0
10011,Keep it going,10202;10082;10068;10199;10120;10119,4,7,5.33,32,6,Justin Wagers,2021,,,0
10012,Magic Tricks,10115;10124,7,8,7.5,15,2,Justin Wagers,2021,https://www.instagram.com/p/CXd2bgnF2W0/,,0
10013,Davis' favorite #1,10169;10066;10120;10119,4,7,5.5,22,4,Davis Hermes,2021,,,0
10014,Davis' favorite #2,10124;10150,8,9,8.5,17,2,Davis Hermes,2021,https://www.instagram.com/p/CSo8Ajrg3JI/,,0
10015,Delaney's favorite #1,10036;10122,3,7,5,10,2,Delaney Lyman,2021,https://www.instagram.com/p/CTzbWhEF99g/,,0
10016,Ana's favorite #1,10050;10119,4,7,5.5,11,2,Ana Lincoln,2021,,,0
10017,Basti's favorite #1,10124;10143,8,8,8,16,2,Sebastian Egger,2021,https://www.instagram.com/p/CLJKI5yq5e_/,,0
10018,Basti's favorite #2,10077;10071;10050;10223;10119,4,7,4.8,24,5,Sebastian Egger,2021,,,0
10019,Basti's favorite #3,10063;10069;10120,4,7,5,15,3,Sebastian Egger,2021,https://youtu.be/qUxUNfgvoPs?t=112,,0
10020,Backward buttery baguette,10053;10069;10143,4,8,5.33,16,3,Tlaloc Moctezuma-Burns,2021,,,0
10021,Tlaloc's favorite #1,10089;10199;10120,4,7,5.33,16,3,Tlaloc Moctezuma-Burns,2021,,,0
10022,Tlaloc's favorite #2,10080;10079;10042;10104,3,6,4.75,19,4,Tlaloc Moctezume-Burns,2021,,,0`;
