# Script has been derived from @hbarcelos
# https://github.com/lint-staged/lint-staged/issues/1198#issue-1337493947
name: Linting

on:
  pull_request:
    branches:
      - main
      - develop
      - rewrite

jobs:
  lint:
    name: Run ESLint and Prettier for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Install Dependencies from Lock-File
        run: npm ci
      - name: Run lint-staged
        # lint-staged gets it's own config for the CI which will not write changes
        # e.g. using prettier --check instead of prettier --write
        run: npx lint-staged --config .lintstagedrc-ci --diff="origin/${GITHUB_BASE_REF}...origin/${GITHUB_HEAD_REF}"
