name: Linting

on:
  pull_request:
    branches:
      - main
      - develop
      - rewrite
      
jobs:
  lint:
    name: Run ESLint and Prettier for changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Install Dependencies from Lock-File
        run: npm ci
      - name: Run Eslint
        run: npm run lint:eslint
      - name: Run Prettier
        run: npm run lint:prettier
